// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimePhysique.Models;

#nullable disable

namespace PrimePhysique.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimePhysique.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Suplementos"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pre-entrenos"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Proteínas"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Creatinas"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Hoodies"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Pantalones"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Playeras de Compresión"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Accesorios"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Camisetas"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Camisetas de Manga Larga"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Tanks"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Quema Grasas"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Aminoácidos"
                        });
                });

            modelBuilder.Entity("PrimePhysique.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "https://www.youngla.com/cdn/shop/files/spaced_logo_Black_32dec808-d736-4b71-87a2-b92272e92b0a.png?v=1742116144&width=2745",
                            Nombre = "YoungLA"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "https://cdn.gymshark.com/images/branding/gs-icon-text.svg",
                            Nombre = "Gymshark"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "https://www.evogennutrition.com/cdn/shop/files/Evogen-Brand-Logo.jpg?height=150&v=1626896369",
                            Nombre = "Evogen Nutrition"
                        },
                        new
                        {
                            Id = 4,
                            LogoUrl = "https://proteinpalacemx.com/cdn/shop/collections/DRAGON_PHARMA_590x.jpg?v=1631223146",
                            Nombre = "Dragon Pharma"
                        });
                });

            modelBuilder.Entity("PrimePhysique.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Sabor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TallaColorInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 10,
                            Descripcion = "Playera de algodón premium con corte oversize, ideal para el gimnasio o uso casual. Comodidad y estilo.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/products/DSC08705-11.jpg?v=1720554448&width=300",
                            MarcaId = 1,
                            Nombre = "Playera Oversize 'Signature'",
                            Precio = 35.99m,
                            TallaColorInfo = "Tallas: M, L, XL | Colores: Negro, Gris, Blanco, Roja"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 6,
                            Descripcion = "Sudadera con capucha de tejido suave y ajuste atlético. Perfecta para el calentamiento o el día a día.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/LegacyHoodieBlackA5A2X-BB2J-0733_384x.jpg?v=1722505055",
                            MarcaId = 2,
                            Nombre = "Hoodie 'Legacy'",
                            Precio = 59.99m,
                            TallaColorInfo = "Tallas: S, M, L | Colores: Verde, Negro, Azul"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Contenido = "20 servicios",
                            Descripcion = "Fórmula de pre-entreno sin estimulantes diseñada para maximizar el bombeo muscular y la hidratación. Ideal para entrenamientos intensos.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/EVP_AQ_SourApple.png?crop=center&height=540&v=1722693127&width=540",
                            MarcaId = 3,
                            Nombre = "Pre-entreno EVP-AQ",
                            Precio = 45.00m,
                            Sabor = "Ponche de Frutas"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Contenido = "2 Lbs",
                            Descripcion = "Aislado de proteína de suero de leche de rápida absorción, ideal para la recuperación post-entrenamiento. Baja en carbohidratos y grasas.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0049_iso-phrom-whitechocolate-2L-front_720x.png?v=1691498671",
                            MarcaId = 4,
                            Nombre = "Proteína IsoPhorm",
                            Precio = 70.00m,
                            Sabor = "Chocolate"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 11,
                            Descripcion = "Camiseta de manga larga sin costuras, ajuste muscular. Ideal para entrenamientos de alto rendimiento.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-ShadowLSMuscleFitTeeGSBlackA1B5B_BB2J_1219_384x.jpg?v=1746634334",
                            MarcaId = 2,
                            Nombre = "Shadow Seamless Long Sleeve T-Shirt",
                            Precio = 36.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Meteor Grey, Black, Faded Blue"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 10,
                            Descripcion = "Camiseta acanalada de ajuste muscular, cómoda y estilosa para el gimnasio o el día a día.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-RibbedMuscleT_ShirtGSBlackA2B5T_BB2J_1267_0175_384x.jpg?v=1747813607",
                            MarcaId = 2,
                            Nombre = "Ribbed T-Shirt",
                            Precio = 19.20m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Black, White, Stone Grey Marl"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 8,
                            Descripcion = "Camiseta de capa base con ajuste de compresión, diseñada para un rendimiento óptimo.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-GFXLifting6BaselayerT_ShirtGSBlackA2B7Q_BB2J_0752_384x.jpg?v=1747685881",
                            MarcaId = 2,
                            Nombre = "GSLC Baselayer T-Shirt",
                            Precio = 27.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Black, White"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 11,
                            Descripcion = "Camiseta de manga larga de capa base con ajuste de compresión, ideal para cualquier actividad.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-ElementBaselayerGSStrengthGreenT_ShirtA2B4C_ECJH_0151_384x.jpg?v=1747311667",
                            MarcaId = 2,
                            Nombre = "Element Baselayer Long Sleeve T-Shirt",
                            Precio = 27.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: White, Dark Grey"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 12,
                            Descripcion = "Tank top con ajuste de compresión, perfecto para entrenamientos intensos y máxima movilidad.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-ElementTankGSCarmineRed_GSBlackA2C4U_RB2R_0225_384x.jpg?v=1747311526",
                            MarcaId = 2,
                            Nombre = "Element Tank",
                            Precio = 19.80m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: White, Carmine Red"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 10,
                            Descripcion = "Camiseta de punto urdido, diseño moderno y tejido ligero para el uso diario.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-everywearWarpKnitT_ShirtGSBlackA1B9Y_BB2J_1210_384x.jpg?v=1748293907",
                            MarcaId = 2,
                            Nombre = "everywear Warp Knit T-Shirt",
                            Precio = 77.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Black, Tame Grey, Pale Blue"
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 10,
                            Descripcion = "Camiseta sin costuras con ajuste muscular, patrón tectónico para un look distintivo.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/TectonicSeamlessTShirtGSAsphaltGrey-GSBlackA1B1P-GCWT-0243_ab73a218-b3b7-4261-a921-23d269f2d1df_384x.jpg?v=1733829349",
                            MarcaId = 2,
                            Nombre = "Tectonic Seamless T Shirt",
                            Precio = 22.80m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Asphalt Grey/Black, Cargo Blue/Cool Blue, Trail Green/Classic Green"
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 6,
                            Descripcion = "Sudadera con cremallera de 1/4 sin costuras, ajuste delgado, perfecta para capas.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/CleanContourSeamlessSportsBraGSBlackB2C1I-BB2J6351_08e31e70-5086-454e-83a3-9779061fcfb2_1920x.jpg?v=1735645373",
                            MarcaId = 2,
                            Nombre = "Clean Contour Seamless 1/4 Zip",
                            Precio = 30.80m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Black/White"
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 12,
                            Descripcion = "Tank top de compresión Onyx 5.0, diseñado para un soporte y libertad de movimiento superiores.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-Onyx5_0TankGSBlackGSCarmineRedA1B1N_BB4J_5412_A_640x.jpg?v=1746629027",
                            MarcaId = 2,
                            Nombre = "Onyx 5.0 Tank",
                            Precio = 44.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Black/Light Grey, Black/Carmine Red, Black/Onyx Grey"
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 11,
                            Descripcion = "Camiseta de manga larga sin costuras Onyx 5.0, ajuste de compresión para un rendimiento máximo.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-Onyx5_0SeamlessLST_ShirtSS25GSBlackGSLightGreyA6A3G_BB23_5385_6e9b9a93-3a9e-4982-88a4-926b484f2df4_640x.jpg?v=1746628707",
                            MarcaId = 2,
                            Nombre = "Onyx 5.0 Seamless Long Sleeve T-Shirt",
                            Precio = 56.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Black/Light Grey, Black/Carmine Red, Black/Onyx Grey"
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 8,
                            Descripcion = "Camiseta sin costuras Onyx 5.0, ajuste de compresión para un soporte óptimo durante el ejercicio.",
                            ImagenUrl = "https://cdn.shopify.com/s/files/1/0156/6146/files/images-A6A3G_BB24_8_640x.jpg?v=1746696933",
                            MarcaId = 2,
                            Nombre = "Onyx 5.0 Seamless T-Shirt",
                            Precio = 50.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Black/Light Grey, Black/Carmine Red, Black/Onyx Grey"
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 8,
                            Descripcion = "Camiseta de compresión con diseño de Superman, ideal para entrenamientos o uso casual. Ajuste ceñido.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/YLA5.30_baeb29b0-ea4a-4d22-838e-428a7f9c6fa3.jpg?v=1751418341&width=300",
                            MarcaId = 1,
                            Nombre = "4117 - Camiseta de Compresión Superman",
                            Precio = 45.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Negro, Azul, Carbón, Rojo"
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 10,
                            Descripcion = "Camiseta de algodón con gráficos icónicos de Superman. Perfecta para mostrar tu lado heroico.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/4044_chrome-logo_003_07_01_bryan_lifestyle_a3e17d95-0c82-4af4-9e39-fe1e6292db43.jpg?v=1751418166&width=1000",
                            MarcaId = 1,
                            Nombre = "4044 - Camiseta Gráfica de Superman",
                            Precio = 42.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Diseños: Logotipo de Chrome, En acción, Legado, Limitado al espacio, La pintura"
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 10,
                            Descripcion = "Camisa raglán 3/4 con diseño de Superman, cómoda y con estilo deportivo.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/8072_black-red_004_07_01_bryan_lifestyle.jpg?v=1750966526&width=300",
                            MarcaId = 1,
                            Nombre = "8072 - Camisa Raglán 3/4 de Superman",
                            Precio = 45.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Negro/Rojo, Blanco y negro, Blanco/Azul"
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 6,
                            Descripcion = "Sudadera con capucha de alta calidad con el legado de Superman, ideal para el frío.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/YLA5.27_92dd2563-c481-407e-b49b-578fdc72ab50.jpg?v=1750966138&width=200",
                            MarcaId = 1,
                            Nombre = "5079 - Sudadera con Capucha del Legado de Superman",
                            Precio = 62.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Lavado negro, Lavado azul, Gris brezo"
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 12,
                            Descripcion = "Camiseta sin mangas estilo cut-off de Superman, perfecta para mostrar tus músculos en el gimnasio.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/YLA5.2220_da90ba32-ef1c-47ef-8316-47e67fec04de.jpg?v=1751418105&width=200",
                            MarcaId = 1,
                            Nombre = "3004 - Superman Cut-Offs",
                            Precio = 40.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Diseños: A prueba de balas, Limitado al espacio, La pintura"
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 7,
                            Descripcion = "Sudadera cómoda de Superman, ideal para el uso diario y para los fans del héroe.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/YLA5.3e0_33bd2e66-10f6-4785-b963-12bf50a10326.jpg?v=1750973332&width=200",
                            MarcaId = 1,
                            Nombre = "2032 - Superman Sudadera",
                            Precio = 62.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Lavado negro, Lavado azul, Gris brezo"
                        },
                        new
                        {
                            Id = 22,
                            CategoriaId = 9,
                            Descripcion = "Gorra con el icónico escudo de Superman, un accesorio imprescindible para cualquier fan.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/YLA5.210.jpg?v=1750886929&width=200",
                            MarcaId = 1,
                            Nombre = "9092 - Sombrero Escudo de Superman",
                            Precio = 36.00m,
                            TallaColorInfo = "Talla: Única | Colores: Negro, Gris claro, Rojo"
                        },
                        new
                        {
                            Id = 23,
                            CategoriaId = 7,
                            Descripcion = "Pantalones deportivos cómodos y versátiles, perfectos para entrenar o relajarse.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/YLA_10.2_13761032-5736-4c6a-a4d0-3fd4dd79e5b3.jpg?v=1699481570&width=200",
                            MarcaId = 1,
                            Nombre = "249 - Pantalones Deportivos Flagship",
                            Precio = 50.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL, XXL | Colores: Negro, Borgoña, Morado oscuro, Verde jungla, Blanquecino, Neón negro, Carbón, Marina de guerra, Gris, Rojo, Gris azul"
                        },
                        new
                        {
                            Id = 24,
                            CategoriaId = 10,
                            Descripcion = "Camiseta con diseño de guerrero, ideal para un estilo audaz y motivador.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/Jerdani_WarriorTee-28.jpg?v=1714602066&width=200",
                            MarcaId = 1,
                            Nombre = "4118 - Camiseta de Guerrero",
                            Precio = 34.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Lavado negro, Lavado gris, Lavado azul claro, Lavado rosa"
                        },
                        new
                        {
                            Id = 25,
                            CategoriaId = 10,
                            Descripcion = "Camiseta corta de base, ideal para entrenamientos intensos y para mantener la frescura.",
                            ImagenUrl = "https://www.youngla.com/cdn/shop/files/4138_forest-green-wash_0016_06_25_johnny_ecomm_5f8af11d-c9b3-4f68-9d6c-48b4bb83a6cf.jpg?v=1719336250&width=200",
                            MarcaId = 1,
                            Nombre = "4138 - Camiseta Corta de Base",
                            Precio = 36.00m,
                            TallaColorInfo = "Tallas: XS, S, M, L | Colores: Lavado negro, Lavado marrón, Lavado verde bosque, Lavado gris"
                        },
                        new
                        {
                            Id = 26,
                            CategoriaId = 4,
                            Contenido = "5 Lbs",
                            Descripcion = "Ganador de masa muscular diseñado para maximizar el crecimiento y la recuperación. Alto en calorías y proteínas.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0068_Mockup-Mass-Phorm-Dragon-Pharma-Vanilla-Milkshake-Pose-3_720x.png?v=1691498083",
                            MarcaId = 4,
                            Nombre = "MASSPHORM - Ganador de Masa Definitivo",
                            Precio = 69.00m,
                            Sabor = "Chocolate, Vainilla"
                        },
                        new
                        {
                            Id = 27,
                            CategoriaId = 4,
                            Contenido = "2 Lbs",
                            Descripcion = "Proteína de suero de alta calidad para el desarrollo y mantenimiento muscular. Excelente sabor y disolución.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/Mockup-WheyPhorm-2Lb-BirthdayCake-Pose1_bcc559b4-706d-4800-8b69-20e434a42bcf_720x.png?v=1732523043",
                            MarcaId = 4,
                            Nombre = "WHEYPHORM® - Proteína de Suero",
                            Precio = 49.90m,
                            Sabor = "Chocolate, Vainilla, Fresa"
                        },
                        new
                        {
                            Id = 28,
                            CategoriaId = 14,
                            Contenido = "30 servicios",
                            Descripcion = "Fórmula completa de aminoácidos esenciales (EAA) para la recuperación y el rendimiento. Ideal intra-entrenamiento.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0005_dr-feaar-v2-peach-guava-front_720x.png?v=1691501874",
                            MarcaId = 4,
                            Nombre = "DR. FEAAR® - Aminoácido Esencial Completo",
                            Precio = 45.00m,
                            Sabor = "Blue Raspberry, Mango"
                        },
                        new
                        {
                            Id = 29,
                            CategoriaId = 3,
                            Contenido = "50 servicios",
                            Descripcion = "Pre-entrenamiento termogénico diseñado para energía extrema, enfoque y quema de grasa. Sabor limón.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023-venom-cotton-candy_720x.png?v=1740674377",
                            MarcaId = 4,
                            Nombre = "VENOM INFERNO - Pre-entrenamiento",
                            Precio = 49.99m,
                            Sabor = "Limón"
                        },
                        new
                        {
                            Id = 30,
                            CategoriaId = 2,
                            Contenido = "60 cápsulas",
                            Descripcion = "Suplemento para el desarrollo muscular y la fuerza, optimizado para mujeres. Soporte hormonal natural.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0028_new-fema-front_720x.png?v=1691501701",
                            MarcaId = 4,
                            Nombre = "FEMATROPE®",
                            Precio = 79.99m
                        },
                        new
                        {
                            Id = 31,
                            CategoriaId = 5,
                            Contenido = "60 servicios",
                            Descripcion = "Sistema de creatina avanzado para aumentar la fuerza, potencia y resistencia muscular. Sin hinchazón.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0002_atp-force-v2-ppina-colada-front_720x.png?v=1697047885",
                            MarcaId = 4,
                            Nombre = "ATP Force - Sistema de Creatina Mejorado",
                            Precio = 45.00m,
                            Sabor = "Sin Sabor"
                        },
                        new
                        {
                            Id = 32,
                            CategoriaId = 2,
                            Contenido = "80 cápsulas",
                            Descripcion = "Diurético natural para ayudar a eliminar el exceso de agua y lograr una apariencia más definida.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0026_new-dryup-front_720x.png?v=1691501775",
                            MarcaId = 4,
                            Nombre = "DRYUP® - Diurético Natural",
                            Precio = 34.99m
                        },
                        new
                        {
                            Id = 33,
                            CategoriaId = 14,
                            Contenido = "300g",
                            Descripcion = "Glutamina de alta pureza para la recuperación muscular y el soporte del sistema inmunológico.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0018_Mockup---Glutamine-Essentials---Dragon-Pharma---Sem-Fundo1_720x.png?v=1691501674",
                            MarcaId = 4,
                            Nombre = "GLUTAMINA FERMENTADA",
                            Precio = 24.90m,
                            Sabor = "Sin Sabor"
                        },
                        new
                        {
                            Id = 34,
                            CategoriaId = 2,
                            Contenido = "30 servicios",
                            Descripcion = "Mezcla de superalimentos verdes y rojos para soporte nutricional completo y antioxidantes.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0014_Mockup---Dragon-Pharma---Reds-n-Greens---Lemonade---Posicao-1_720x.png?v=1691501627",
                            MarcaId = 4,
                            Nombre = "VERDES Y ROJOS - Superalimentos",
                            Precio = 44.99m,
                            Sabor = "Berry Blast"
                        },
                        new
                        {
                            Id = 35,
                            CategoriaId = 13,
                            Contenido = "30 servicios",
                            Descripcion = "L-Carnitina líquida de alta potencia para la quema de grasa y la producción de energía.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/products/600x600-lcarnitine-mango-1_720x.png?v=1695741775",
                            MarcaId = 4,
                            Nombre = "L-CARNITINA-3000",
                            Precio = 34.99m,
                            Sabor = "Manzana Verde"
                        },
                        new
                        {
                            Id = 36,
                            CategoriaId = 2,
                            Contenido = "30 servicios",
                            Descripcion = "Suplemento de hidratación avanzada con electrolitos y minerales para optimizar el rendimiento.",
                            ImagenUrl = "https://dragonpharmalabs.com/cdn/shop/files/RENDERS-600X600-2023_0029_Mockup---Hydra---Dragon-Pharma---Pose-1_720x.png?v=1691502355",
                            MarcaId = 4,
                            Nombre = "HYDRA - Hidratación Avanzada",
                            Precio = 79.99m,
                            Sabor = "Sandía"
                        },
                        new
                        {
                            Id = 37,
                            CategoriaId = 13,
                            Contenido = "90 cápsulas",
                            Descripcion = "CLA de alta pureza para apoyar la composición corporal y la quema de grasa.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/CLA_0624_bottle_1200x1200_443cdc93-72d0-4f90-a25f-912da81c9c87.png?v=1724779938&width=900",
                            MarcaId = 3,
                            Nombre = "CLA - Ácido Linoleico Conjugado",
                            Precio = 19.95m
                        },
                        new
                        {
                            Id = 38,
                            CategoriaId = 2,
                            Contenido = "60 cápsulas",
                            Descripcion = "Vitamina D3 esencial para la salud ósea, el sistema inmunológico y el bienestar general.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/VitaminD3_0524render_1.png?v=1724778512&width=900",
                            MarcaId = 3,
                            Nombre = "Vitamina D3",
                            Precio = 12.99m
                        },
                        new
                        {
                            Id = 39,
                            CategoriaId = 2,
                            Contenido = "14 días",
                            Descripcion = "Programa de limpieza y desintoxicación digestiva de 14 días para una sensación ligera y firme.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/Light_TightFront1123.png?v=1709738054&width=900",
                            MarcaId = 3,
                            Nombre = "Light & Tight - Limpieza Digestiva",
                            Precio = 29.95m
                        },
                        new
                        {
                            Id = 40,
                            CategoriaId = 2,
                            Contenido = "120 cápsulas",
                            Descripcion = "Potenciador natural de testosterona para mejorar la fuerza, el rendimiento y la vitalidad.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/Evoboostrenderrebuild.png?v=1702568583&width=900",
                            MarcaId = 3,
                            Nombre = "Evoboost-T - Potenciador de Testosterona",
                            Precio = 64.95m
                        },
                        new
                        {
                            Id = 41,
                            CategoriaId = 14,
                            Contenido = "200g",
                            Descripcion = "L-Citrulina en polvo para mejorar el flujo sanguíneo, el bombeo muscular y la resistencia.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/renderCITRULLINE.jpg?v=1727985466&width=900",
                            MarcaId = 3,
                            Nombre = "Polvo de L-Citrulina",
                            Precio = 27.99m,
                            Sabor = "Sin Sabor"
                        },
                        new
                        {
                            Id = 42,
                            CategoriaId = 14,
                            Contenido = "200g",
                            Descripcion = "Beta-Alanina en polvo para aumentar la resistencia muscular y reducir la fatiga durante el ejercicio.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/renderBetaAlaninerender02.jpg?v=1727985106&width=900",
                            MarcaId = 3,
                            Nombre = "Polvo de Beta-Alanina",
                            Precio = 19.95m,
                            Sabor = "Sin Sabor"
                        },
                        new
                        {
                            Id = 43,
                            CategoriaId = 2,
                            Contenido = "60 cápsulas",
                            Descripcion = "Optimizador de nutrientes para ayudarte a aprovechar al máximo tus comidas trampa sin remordimientos.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/EVOLOGasset.jpg?v=1703292233&width=900",
                            MarcaId = 3,
                            Nombre = "Evolog - Ganancias con Comidas Trampa",
                            Precio = 39.95m
                        },
                        new
                        {
                            Id = 44,
                            CategoriaId = 13,
                            Contenido = "30 servicios",
                            Descripcion = "Carnitina líquida de alta calidad para la movilización de grasas y la producción de energía.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/Carnigen_new_blue_label_grape_24.png?v=1733491617&width=900",
                            MarcaId = 3,
                            Nombre = "Carnitina Líquida Premium Carnigen",
                            Precio = 34.95m,
                            Sabor = "Mango"
                        },
                        new
                        {
                            Id = 45,
                            CategoriaId = 13,
                            Contenido = "30 servicios",
                            Descripcion = "Termogénico en polvo de acción rápida para quemar grasa y aumentar la energía. Sabor refrescante.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/LipocideIR_GRAPECC.png?v=1716135069&width=900",
                            MarcaId = 3,
                            Nombre = "Polvo Termogénico Lipocide IR",
                            Precio = 49.95m,
                            Sabor = "Ponche de Frutas"
                        },
                        new
                        {
                            Id = 46,
                            CategoriaId = 4,
                            Contenido = "2 Lbs",
                            Descripcion = "Mezcla de proteínas de liberación sostenida para una recuperación y crecimiento muscular óptimos.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/Evofusion_2lbvanillabean1223.png?v=1719718852&width=900",
                            MarcaId = 3,
                            Nombre = "Mezcla de Proteínas Evofusion",
                            Precio = 44.95m,
                            Sabor = "Chocolate, Vainilla"
                        },
                        new
                        {
                            Id = 47,
                            CategoriaId = 10,
                            Descripcion = "Camiseta con el logo distintivo de Evogen en forma de arco. Comodidad para el día a día.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/evogenarcbluetee.jpg?v=1716434815&width=900",
                            MarcaId = 3,
                            Nombre = "Camiseta de Arco",
                            Precio = 35.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Negro, Gris"
                        },
                        new
                        {
                            Id = 48,
                            CategoriaId = 7,
                            Descripcion = "Joggers modernos y cómodos, ideales para el gimnasio o el estilo de vida activo.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/Olympiaassetsgreyjogger.jpg?v=1700195164",
                            MarcaId = 3,
                            Nombre = "Joggers de Última Generación",
                            Precio = 50.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Negro, Gris"
                        },
                        new
                        {
                            Id = 49,
                            CategoriaId = 6,
                            Descripcion = "Sudadera con capucha de diseño moderno, perfecta para mantenerte abrigado y con estilo.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/files/12_20_drop_hoodie_01.jpg?v=1734657585&width=900",
                            MarcaId = 3,
                            Nombre = "Sudadera con Capucha de Última Generación",
                            Precio = 55.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Colores: Negro, Azul"
                        },
                        new
                        {
                            Id = 50,
                            CategoriaId = 9,
                            Descripcion = "Cinturón de cuero resistente de 6mm para soporte lumbar en levantamientos pesados.",
                            ImagenUrl = "https://www.evogennutrition.com/cdn/shop/products/BeltBackView.jpg?v=1630508778&width=900",
                            MarcaId = 3,
                            Nombre = "Cinturón de Levantamiento de Cuero Clásico 6mm",
                            Precio = 75.00m,
                            TallaColorInfo = "Tallas: S, M, L, XL | Color: Negro"
                        });
                });

            modelBuilder.Entity("PrimePhysique.Models.Producto", b =>
                {
                    b.HasOne("PrimePhysique.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimePhysique.Models.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("PrimePhysique.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PrimePhysique.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
